### ISSUE TITLE
What do the parameters mean in the configuration file?

### ISSUE THREAD

**Issue by wanggy-1** [erosiv/soillib#16]
In [tools/basic_hydrology/config.yaml](https://github.com/erosiv/soillib/blob/main/tools/basic_hydrology/config.yaml), What are the meanings of those parameters and how do they affect the geomorphology? For example, if I don't want to create any lake or pool, how should I adjust these parameters?

```
lrate: 0.1
scale: 80
max-cycles: 8192
min-basin: 0.05
map:
  dimension:
    - 960
    - 960
water:
  max-age: 1024
  evap-rate: 0.001
  deposition-rate: 0.05
  min-vol: 0.001
  entrainment: 10.0
  gravity: 2.0
  momentum-transfer: 1.0
```
